### ISSUE TITLE
Requirement for Python 3.12 

### ISSUE THREAD

**Issue by Zeleni9** [JosefAlbers/whisper-turbo-mlx#4]
Hey, thanks for providing another implementation for Whisper Turbo, I tried installing it, but it requires Python 3.12 is that really neccessary to pip install it?

**Comment by JosefAlbers** [comment]
Well, you don't have to pip install it - the entire thing (whisper model, tokenizer, and all the loading/inference code) is contained within that short snippet of code in a single file, so you can try running it directly from source. The pip install is mainly there to give you the convenient `wtm` command instead of typing something like `python path/to/code/whisper-turbo-mlx` each time.

Regarding Python 3.12 - pip should still let you install it with earlier Python versions, even though 3.12 is listed in the metadata. Just keep in mind there might be compatibility issues depending on what Python features the code uses.

Let me know if you run into any issues!
